{
 "title": "node_exporter_basics",
 "description": "Basic node exporter dashboard",
 "tags": [
  "linux",
  "node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": "node_exporter_build_info" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Root filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=~\"/(data)?\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{instance=\"$instance\",mountpoint=~\"/(data)?\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Root filesystem size",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\", mountpoint=~\"/(data)?\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(avg by (mode, instance) (irate(node_cpu_seconds_total{instance=\"$instance\", mode!=\"idle\"}[5m])), \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "{{ instance }}/{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace((node_memory_MemTotal_bytes{instance=\"$instance\"}), \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "{{ instance }}/total"
    },
    {
     "expr": "label_replace(node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"}, \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "{{ instance }}/used"
    },
    {
     "expr": "label_replace((node_memory_SwapTotal_bytes{instance=\"$instance\"} - node_memory_SwapFree_bytes{instance=\"$instance\"}), \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "{{ instance }}/swap"
    },
    {
     "expr": "label_replace((node_memory_Cached_bytes{instance=\"$instance\"} + node_memory_Buffers_bytes{instance=\"$instance\"}), \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "{{ instance }}/cache+buffers"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(node_network_receive_bytes_total{instance=\"$instance\",device!~\"lo\"}[5m]), \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "Rx: {{ instance }}/{{ device }}"
    },
    {
     "expr": "label_replace(irate(node_network_transmit_bytes_total{instance=\"$instance\",device!~\"lo\"}[5m]), \"instance\", \"$1\", \"instance\", \"([^:]+):.+\")",
     "legendFormat": "Tx: {{ instance }}/{{ device }}"
    }
   ]
  }
 ]
}