# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../utils/vagrant_defaults'

Vagrant.configure(2) do |config|
  config.vm.synced_folder "..", "/vagrant"

  config.vm.define "prometheus" do |prometheus|
    prometheus.vm.box = BOX
    prometheus.vm.provider "virtualbox" do |vbox|
      vbox.gui    = GUI
      vbox.memory = RAM
      vbox.name = "prometheus"
    end
    prometheus.vm.hostname = "prometheus" + DOMAIN
    prometheus.vm.network 'private_network', ip: NETWORK + "10", netmask: NETMASK
    prometheus.vm.network "forwarded_port", guest: 9090, host: 9090
    prometheus.vm.provision "shell", path: "provision/prometheus.sh"
  end

end
