#!/usr/bin/env python3

from http.server import HTTPServer, BaseHTTPRequestHandler
import json
import socket


class RequestHandler(BaseHTTPRequestHandler):

    def do_POST(self):
        content_len = int(self.headers['Content-Length'])
        body = self.rfile.read(content_len)
        self.send_response(200)
        self.end_headers()
        json_payload = json.loads(body)
        with open("/vagrant/cache/" + socket.gethostname() + ".log", "a") as logfile:
            logfile.write(json.dumps(json_payload, indent=4))


webserver = HTTPServer(('127.0.0.1', 5001), RequestHandler)
webserver.serve_forever()
